### ISSUE TITLE
Accès à la correction : pas de changement de valeur

### ISSUE THREAD

**Issue by stephanebarcet** [sfraysse/moodle-scormlite#1]
Je créé une activité Scormlite. Je mets le paramètres "Accès à la correction" sur "Après réussite...". J'enregistre.
Je reviens dans les paramètres, je regarde le paramètre "accès à la correction". Il est toujours sur "Immédiat".

**Comment by sfraysse** [comment]
OK, le problème existe sur les activités existantes qui avaient la case à cocher "Immediate access" cochée.
